### ISSUE TITLE
пакет в карго

### ISSUE THREAD

**Issue by edvorg** [inferrna/alor_api_rust#1]
есть ли планы запаблишить этот клиент?

**Comment by inferrna** [comment]
Нет, лучше использовать как основу для своего клиента и далее вносить правки. По двум причинам:
1. Сам Алор не использует кодогенерацию для официальных клиентов и для тестирования, соответственно, непонятно, насколько их сваггер вообще соотносится с апи.
2. Я генерирую из автоматически модифицированного сваггера, где попытался исправить косяки алора. При этом делаю множество шатких допущений: например при слиянии типов я исхожу из того, что параметр с одним именем всюду, скорее всего, должен иметь один тип, что для какого-то случая может быть неверно.

как видите, это не случай "подключил либу и спокойно пользуюсь", а код "форкнул болванку и постоянно правлю"

**Comment by edvorg** [comment]
Может стоит попробовать предложить фиксы для сваггера в апстрим?
